package org.minecraft;

public interface WolfObjects {
    int PLAYER_NORTH = 19;
    int PLAYER_EAST = 20;
    int PLAYER_SOUTH = 21;
    int PLAYER_WEST = 22;

    int WATER = 23;
    int OIL_DRUM = 24;
    int TABLE_WITH_CHAIRS = 25;
    int FLOOR_LAMP = 26;
    int CHANDELIER = 27;
    int HANGING_SKELETON = 28;
    int DOG_FOOD = 29;
    int WHITE_COLUMN = 30;
    int GREEN_PLANT = 31;
    int SKELETON = 32;
    int SINK_SKULLS_ON_STICK = 33;
    int BROWN_PLANT = 34;
    int VASE = 35;
    int TABLE = 36;
    int CEILING_LIGHT_GREEN = 37;
    int UTENSILS_BROWN_CAGE_BLOODY_BONES = 38;
    int ARMOR = 39;
    int CAGE = 40;
    int CAGE_SKELETON = 41;
    int BONES1 = 42;
    int KEY_GOLD = 43;
    int KEY_SILVER = 44;
    int BED_CAGE_SKULLS = 45;
    int BASKET = 46;
    int FOOD = 47;
    int MEDKIT = 48;
    int AMMO = 49;
    int MACHINE_GUN = 50;
    int CHAIN_GUN = 51;
    int CROSS = 52;
    int CHALICE = 53;
    int CHEST = 54;
    int CROWN = 55;
    int LIFE = 56;
    int BONES_BLOOD = 57;
    int BARREL = 58;
    int WELL_WATER = 59;
    int WELL = 60;
    int POOL_OF_BLOOD = 61;
    int FLAG = 62;
    int CEILING_LIGHT_RED_AARDWOLF = 63;
    int BONES2 = 64;
    int BONES3 = 65;
    int BONES4 = 66;
    int UTENSILS_BLUE_COW_SKULL = 67;
    int STOVE_WELL_BLOOD = 68;
    int RACK_ANGEL_STATUE = 69;
    int VINES = 70;
    int BROWN_COLUMN = 71;
    int AMMO_BOX = 72;
    int TRUCK_REAR = 73;
    int SPEAR = 74;

    int PUSHABLE_WALL = 98;
    int ENDGAME = 99;

    int SPECTRE = 106;
    int ANGEL = 107;

    int STANDING_GUARD_EASY_NORTH = 108;
    int STANDING_GUARD_EASY_EAST = 109;
    int STANDING_GUARD_EASY_SOUTH = 110;
    int STANDING_GUARD_EASY_WEST = 111;

    int PATROLLING_GUARD_EASY_NORTH = 112;
    int PATROLLING_GUARD_EASY_EAST = 113;
    int PATROLLING_GUARD_EASY_SOUTH = 114;
    int PATROLLING_GUARD_EASY_WEST = 115;

    int STANDING_OFFICER_EASY_NORTH = 116;
    int STANDING_OFFICER_EASY_EAST = 117;
    int STANDING_OFFICER_EASY_SOUTH = 118;
    int STANDING_OFFICER_EASY_WEST = 119;

    int PATROLLING_OFFICER_EASY_NORTH = 120;
    int PATROLLING_OFFICER_EASY_EAST = 121;
    int PATROLLING_OFFICER_EASY_SOUTH = 122;
    int PATROLLING_OFFICER_EASY_WEST = 123;

    int DEAD_GUARD = 124;
    int TRANS = 126;

    int STANDING_SS_EASY_NORTH = 126;
    int STANDING_SS_EASY_EAST = 127;
    int STANDING_SS_EASY_SOUTH = 128;
    int STANDING_SS_EASY_WEST = 129;

    int PATROLLING_SS_EASY_NORTH = 130;
    int PATROLLING_SS_EASY_EAST = 131;
    int PATROLLING_SS_EASY_SOUTH = 132;
    int PATROLLING_SS_EASY_WEST = 133;

    int STANDING_DOG_EASY_NORTH = 134;
    int STANDING_DOG_EASY_EAST = 135;
    int STANDING_DOG_EASY_SOUTH = 136;
    int STANDING_DOG_EASY_WEST = 137;

    int PATROLLING_DOG_EASY_NORTH = 138;
    int PATROLLING_DOG_EASY_EAST = 139;
    int PATROLLING_DOG_EASY_SOUTH = 140;
    int PATROLLING_DOG_EASY_WEST = 141;

    int UBER_MUTANT = 142;
    int BARNACLE_WILHELM = 143;

    int STANDING_GUARD_MEDIUM_NORTH = 144;
    int STANDING_GUARD_MEDIUM_EAST = 145;
    int STANDING_GUARD_MEDIUM_SOUTH = 146;
    int STANDING_GUARD_MEDIUM_WEST = 147;

    int PATROLLING_GUARD_MEDIUM_NORTH = 148;
    int PATROLLING_GUARD_MEDIUM_EAST = 149;
    int PATROLLING_GUARD_MEDIUM_SOUTH = 150;
    int PATROLLING_GUARD_MEDIUM_WEST = 151;

    int STANDING_OFFICER_MEDIUM_NORTH = 152;
    int STANDING_OFFICER_MEDIUM_EAST = 153;
    int STANDING_OFFICER_MEDIUM_SOUTH = 154;
    int STANDING_OFFICER_MEDIUM_WEST = 155;

    int PATROLLING_OFFICER_MEDIUM_NORTH = 156;
    int PATROLLING_OFFICER_MEDIUM_EAST = 157;
    int PATROLLING_OFFICER_MEDIUM_SOUTH = 158;
    int PATROLLING_OFFICER_MEDIUM_WEST = 159;

    int ROBED_HITLER = 160;
    int DEATH_KNIGHT = 161;

    int STANDING_SS_MEDIUM_NORTH = 162;
    int STANDING_SS_MEDIUM_EAST = 163;
    int STANDING_SS_MEDIUM_SOUTH = 164;
    int STANDING_SS_MEDIUM_WEST = 165;

    int PATROLLING_SS_MEDIUM_NORTH = 166;
    int PATROLLING_SS_MEDIUM_EAST = 167;
    int PATROLLING_SS_MEDIUM_SOUTH = 168;
    int PATROLLING_SS_MEDIUM_WEST = 169;

    int STANDING_DOG_MEDIUM_NORTH = 170;
    int STANDING_DOG_MEDIUM_EAST = 171;
    int STANDING_DOG_MEDIUM_SOUTH = 172;
    int STANDING_DOG_MEDIUM_WEST = 173;

    int PATROLLING_DOG_MEDIUM_NORTH = 174;
    int PATROLLING_DOG_MEDIUM_EAST = 175;
    int PATROLLING_DOG_MEDIUM_SOUTH = 176;
    int PATROLLING_DOG_MEDIUM_WEST = 177;

    int HITLER = 178;
    int FETTGESICHT = 179;

    int STANDING_GUARD_HARD_NORTH = 180;
    int STANDING_GUARD_HARD_EAST = 181;
    int STANDING_GUARD_HARD_SOUTH = 182;
    int STANDING_GUARD_HARD_WEST = 183;

    int PATROLLING_GUARD_HARD_NORTH = 184;
    int PATROLLING_GUARD_HARD_EAST = 185;
    int PATROLLING_GUARD_HARD_SOUTH = 186;
    int PATROLLING_GUARD_HARD_WEST = 187;

    int STANDING_OFFICER_HARD_NORTH = 188;
    int STANDING_OFFICER_HARD_EAST = 189;
    int STANDING_OFFICER_HARD_SOUTH = 190;
    int STANDING_OFFICER_HARD_WEST = 191;

    int PATROLLING_OFFICER_HARD_NORTH = 192;
    int PATROLLING_OFFICER_HARD_EAST = 193;
    int PATROLLING_OFFICER_HARD_SOUTH = 194;
    int PATROLLING_OFFICER_HARD_WEST = 195;

    int SCHABBS = 196;
    int GRETEL = 197;

    int STANDING_SS_HARD_NORTH = 198;
    int STANDING_SS_HARD_EAST = 199;
    int STANDING_SS_HARD_SOUTH = 200;
    int STANDING_SS_HARD_WEST = 201;

    int PATROLLING_SS_HARD_NORTH = 202;
    int PATROLLING_SS_HARD_EAST = 203;
    int PATROLLING_SS_HARD_SOUTH = 204;
    int PATROLLING_SS_HARD_WEST = 205;

    int STANDING_DOG_HARD_NORTH = 206;
    int STANDING_DOG_HARD_EAST = 207;
    int STANDING_DOG_HARD_SOUTH = 208;
    int STANDING_DOG_HARD_WEST = 209;

    int PATROLLING_DOG_HARD_NORTH = 210;
    int PATROLLING_DOG_HARD_EAST = 211;
    int PATROLLING_DOG_HARD_SOUTH = 212;
    int PATROLLING_DOG_HARD_WEST = 213;

    int HANS = 214;
    int OTTO = 215;

    int STANDING_MUTANT_EASY_NORTH = 216;
    int STANDING_MUTANT_EASY_EAST = 217;
    int STANDING_MUTANT_EASY_SOUTH = 218;
    int STANDING_MUTANT_EASY_WEST = 219;

    int PATROLLING_MUTANT_EASY_NORTH = 220;
    int PATROLLING_MUTANT_EASY_EAST = 221;
    int PATROLLING_MUTANT_EASY_SOUTH = 222;
    int PATROLLING_MUTANT_EASY_WEST = 223;

    int PACMAN_GHOST_RED = 224;
    int PACMAN_GHOST_YELLOW = 225;
    int PACMAN_GHOST_ROSE = 226;
    int PACMAN_GHOST_BLUE = 227;

    int STANDING_MUTANT_MEDIUM_NORTH = 234;
    int STANDING_MUTANT_MEDIUM_EAST = 235;
    int STANDING_MUTANT_MEDIUM_SOUTH = 236;
    int STANDING_MUTANT_MEDIUM_WEST = 237;

    int PATROLLING_MUTANT_MEDIUM_NORTH = 238;
    int PATROLLING_MUTANT_MEDIUM_EAST = 239;
    int PATROLLING_MUTANT_MEDIUM_SOUTH = 240;
    int PATROLLING_MUTANT_MEDIUM_WEST = 241;

    int STANDING_MUTANT_HARD_NORTH = 252;
    int STANDING_MUTANT_HARD_EAST = 253;
    int STANDING_MUTANT_HARD_SOUTH = 254;
    int STANDING_MUTANT_HARD_WEST = 255;

    int PATROLLING_MUTANT_HARD_NORTH = 256;
    int PATROLLING_MUTANT_HARD_EAST = 257;
    int PATROLLING_MUTANT_HARD_SOUTH = 258;
    int PATROLLING_MUTANT_HARD_WEST = 259;

    int KERRY_KANGAROO = -1;
    int ERNIE_ELEPHANT = -1;
}
